### ISSUE TITLE
Issue in WithdrawAll function

### ISSUE THREAD

**Issue by vkpatva** [usrbad/simpleAuction#1]
withdrawAll function can be called by owner multiple times until the contract has balance , there should be a check that owner can withdraw only once.

**Comment by usrbad** [comment]
> withdrawAll function can be called by owner multiple times until the contract has balance , there should be a check that owner can withdraw only once.

Oh wow, nice catch! Thank you! This is so stupid mistake  :) Will fix it soon.

**Comment by usrbad** [comment]
Fixed [here](https://github.com/usrbad/simpleAuction/commit/e552c50ceaef00e47b9d39e8d49b630d011ae8f6).
